"use strict";

const canvas=document.querySelector("#game");
const ctx=canvas.getContext("2d");
const $=selector=>document.querySelector(selector);
const W=canvas.width,H=canvas.height;
const lanes=[H*.50,H*.64,H*.78];
const ui={home:$("#homeScreen"),race:$("#raceScreen"),frame:$(".race-frame"),result:$("#resultScreen"),pause:$("#pauseScreen"),pauseButton:$("#pauseGame"),fullscreenButton:$("#fullscreenGame"),name:$("#playerName"),speed:$("#speed"),score:$("#score"),distance:$("#distance"),courseBar:$("#courseBar"),boostBar:$("#boostBar"),boostValue:$("#boostValue"),combo:$("#combo"),callout:$("#callout"),countdown:$("#countdown"),board:$("#leaderboard"),lane:$("#laneIndicator strong")};

const raceModes={
  time:{label:"TIME ATTACK",baseSpeed:126,boostSpeed:182,obstacleGap:1,rivalChance:.37,gateGap:300,scoreScale:1},
  sprint:{label:"SPRINT",baseSpeed:144,boostSpeed:202,obstacleGap:1.35,rivalChance:.28,gateGap:245,scoreScale:.85},
  precision:{label:"PRECISION",baseSpeed:118,boostSpeed:170,obstacleGap:.76,rivalChance:.44,gateGap:350,scoreScale:1.35}
};

const mediaQuery=query=>globalThis.matchMedia?.(query).matches||false;
const coarsePointer=mediaQuery("(pointer: coarse)");
const reducedMotion=mediaQuery("(prefers-reduced-motion: reduce)");
const lowPower=(navigator.deviceMemory&&navigator.deviceMemory<=4)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4);
const effectsScale=reducedMotion ? .35 : lowPower ? .5 : coarsePointer ? .72 : 1;
const effectStride=effectsScale<.6?7:effectsScale<1?5:3;

let mode="menu",modeBeforePause="racing",selectedMode="time",finishDistance=3000,last=performance.now(),frame=0,distance=0,score=0,speed=96,topSpeed=96,boost=30,boosting=false,combo=0,passes=0,shake=0,spawnClock=0,gateClock=0,calloutTimer=0,countValue=3,countTimer=0;
let objects=[],spray=[],streaks=[];
let board=readBoard();
const rider={lane:1,x:W*.20,y:lanes[1],targetY:lanes[1],z:0,vz:0,tilt:0,invuln:0};

function readBoard(){try{return JSON.parse(localStorage.getItem("wgp1_time_attack_board")||"[]")}catch{return[]}}
function riderName(){return(ui.name.value.trim().replace(/[^\p{L}\p{N} _-]/gu,"").slice(0,14)||"WGP RIDER").toUpperCase()}
function resetRace(){frame=0;distance=score=combo=passes=shake=spawnClock=gateClock=calloutTimer=0;speed=topSpeed=96;boost=30;boosting=false;objects=[];spray=[];streaks=[];rider.lane=1;rider.y=rider.targetY=lanes[1];rider.z=rider.vz=0;rider.invuln=0;updateUI()}
function openRace(){selectedMode=document.querySelector('input[name="raceMode"]:checked')?.value||"time";finishDistance=Number(document.querySelector('input[name="raceDistance"]:checked')?.value)||3000;resetRace();mode="countdown";last=performance.now();document.body.classList.add("racing");ui.home.hidden=true;$("#leaderboardSection").hidden=true;ui.race.classList.add("active");ui.race.setAttribute("aria-hidden","false");ui.result.classList.remove("active");setPausedUI(false);countValue=3;countTimer=0;showCount("3")}
function backHome(){mode="menu";boosting=false;document.body.classList.remove("racing");ui.race.classList.remove("active");ui.race.setAttribute("aria-hidden","true");ui.result.classList.remove("active");setPausedUI(false);ui.home.hidden=false;$("#leaderboardSection").hidden=false;renderBoard()}
function showCount(value){ui.countdown.textContent=value;ui.countdown.classList.remove("on");void ui.countdown.offsetWidth;ui.countdown.classList.add("on")}
function action(name,on=true){if(mode!=="racing")return;if(name==="lane-up"&&on&&rider.lane>0){rider.lane--;rider.targetY=lanes[rider.lane]}if(name==="lane-down"&&on&&rider.lane<2){rider.lane++;rider.targetY=lanes[rider.lane]}if(name==="jump"&&on&&rider.z===0)rider.vz=19;if(name==="boost")boosting=on}
function setPausedUI(paused){ui.pause.classList.toggle("active",paused);ui.pause.setAttribute("aria-hidden",String(!paused));ui.pauseButton.setAttribute("aria-pressed",String(paused));ui.pauseButton.textContent=paused?"▶":"Ⅱ"}
function togglePause(force){if(!["racing","countdown","paused"].includes(mode))return;const pause=typeof force==="boolean"?force:mode!=="paused";if(pause&&mode!=="paused"){modeBeforePause=mode;mode="paused";boosting=false;setPausedUI(true)}else if(!pause&&mode==="paused"){mode=modeBeforePause;last=performance.now();setPausedUI(false)}}
async function toggleFullscreen(){try{if(!document.fullscreenElement){await ui.frame.requestFullscreen?.();await globalThis.screen?.orientation?.lock?.("landscape").catch(()=>{})}else await document.exitFullscreen?.()}catch{}updateFullscreenButton()}
function updateFullscreenButton(){const active=Boolean(document.fullscreenElement);ui.fullscreenButton.textContent=active?"×":"⛶";ui.fullscreenButton.setAttribute("aria-label",active?"Exit full screen":"Enter full screen")}
function spawnObstacle(){const config=raceModes[selectedMode],lane=Math.floor(Math.random()*3),rival=Math.random()<config.rivalChance;objects.push({type:rival?"rival":"buoy",lane,x:W+150,y:lanes[lane],w:rival?125:48,phase:Math.random()*6,passed:false});const doubleChance=selectedMode==="precision"?.5:.32;if(distance>finishDistance*.3&&Math.random()<doubleChance){const other=(lane+1+Math.floor(Math.random()*2))%3;objects.push({type:"buoy",lane:other,x:W+150,y:lanes[other],w:48,phase:0,passed:false})}}
function spawnGate(){const lane=Math.floor(Math.random()*3);objects.push({type:"gate",lane,x:W+120,y:lanes[lane],w:110,phase:0,passed:false})}
function flash(message){ui.callout.textContent=message;ui.callout.classList.add("show");calloutTimer=82}
function crash(){if(rider.invuln>0)return;rider.invuln=100;shake=20;speed=Math.max(70,speed-35);boost=Math.max(0,boost-22);combo=0;flash("CONTACT · SPEED LOST");for(let i=0;i<Math.round(28*effectsScale);i++)spray.push({x:rider.x,y:rider.y-rider.z,vx:(Math.random()-.5)*12,vy:-Math.random()*10,r:2+Math.random()*6,life:34})}
function finish(){mode="finished";boosting=false;const finalScore=Math.floor(score),entry={name:riderName(),score:finalScore,time:Date.now(),mode:selectedMode,distance:finishDistance};board.push(entry);board=board.sort((a,b)=>b.time-a.time).slice(0,50);localStorage.setItem("wgp1_time_attack_board",JSON.stringify(board));const category=board.filter(item=>(item.mode||"time")===selectedMode&&(item.distance||3000)===finishDistance).sort((a,b)=>b.score-a.score||a.time-b.time),position=category.findIndex(item=>item.time===entry.time)+1;$("#resultScore").textContent=finalScore.toLocaleString();$("#resultRider").textContent=entry.name+" · "+raceModes[selectedMode].label+" · "+finishDistance/1000+" KM";$("#resultPasses").textContent=passes;$("#resultSpeed").textContent=Math.round(topSpeed)+" KM/H";$("#resultPosition").textContent="#"+position;ui.result.classList.add("active");ui.result.setAttribute("aria-hidden","false")}

function update(dt){frame++;if(mode==="countdown"){countTimer+=dt;if(countTimer>.72){countTimer=0;countValue--;if(countValue>0)showCount(countValue);else if(countValue===0)showCount("GO!");else mode="racing"}}
  const config=raceModes[selectedMode],racing=mode==="racing",usingBoost=racing&&boosting&&boost>0,target=usingBoost?config.boostSpeed:config.baseSpeed;speed+=(racing?(target-speed)*.018:(96-speed)*.02)*dt*60;topSpeed=Math.max(topSpeed,speed);if(usingBoost)boost=Math.max(0,boost-.27*dt*60);else if(racing)boost=Math.min(100,boost+.04*dt*60);if(boost<=0)boosting=false;
  if(racing){distance+=speed*.0085*dt*60;score+=speed*.0108*config.scoreScale*dt*60*(1+Math.min(combo,10)*.055);spawnClock+=dt*60;gateClock+=dt*60;const progress=distance/finishDistance,gap=Math.max(52,112-progress*54)*config.obstacleGap;if(spawnClock>gap){spawnClock=0;spawnObstacle()}if(gateClock>config.gateGap){gateClock=0;spawnGate()}if(distance>=finishDistance)finish()}
  rider.y+=(rider.targetY-rider.y)*.20*dt*60;if(rider.z>0||rider.vz>0){rider.vz-=1.12*dt*60;rider.z+=rider.vz*dt*60;if(rider.z<=0){rider.z=0;rider.vz=0;for(let i=0;i<Math.round(12*effectsScale);i++)spray.push({x:rider.x,y:rider.y,vx:-Math.random()*7,vy:-Math.random()*5,r:2+Math.random()*4,life:24})}}rider.tilt+=(Math.sign(rider.targetY-rider.y)*.16-rider.tilt)*.13;if(rider.invuln>0)rider.invuln-=dt*60;
  const scroll=speed*.13*dt*60;objects.forEach(o=>{o.x-=scroll;if(o.type==="rival")o.y=lanes[o.lane]+Math.sin(frame*.034+o.phase)*13;const same=Math.abs(rider.y-o.y)<44,close=o.x<rider.x+72&&o.x+o.w>rider.x-64;if(racing&&!o.passed&&o.x+o.w<rider.x-55){o.passed=true;if(o.type==="gate"&&same){score+=500;boost=Math.min(100,boost+30);combo++;passes++;flash("BOOST GATE +500")}else if(o.type!=="gate"){passes++;if(Math.abs(rider.y-o.y)<100){score+=250;boost=Math.min(100,boost+10);combo++;flash("NEAR MISS +250")}else{score+=80;combo++}}}if(racing&&close&&same&&rider.z<42&&o.type!=="gate")crash()});objects=objects.filter(o=>o.x>-200);
  if(racing&&frame%effectStride===0){spray.push({x:rider.x-48,y:rider.y-rider.z+18,vx:-7-Math.random()*7,vy:-1-Math.random()*4,r:2+Math.random()*5,life:23});if(speed>145)streaks.push({x:W+20,y:H*.32+Math.random()*H*.58,w:80+Math.random()*180,life:13})}spray.forEach(p=>{p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.vy+=.27*dt*60;p.life-=dt*60});spray=spray.filter(p=>p.life>0).slice(-120);streaks.forEach(s=>{s.x-=34*dt*60;s.life-=dt*60});streaks=streaks.filter(s=>s.life>0).slice(-40);shake*=.82;if(calloutTimer>0)calloutTimer-=dt*60;else ui.callout.classList.remove("show");updateUI()}

function updateUI(){ui.speed.textContent=String(Math.round(speed)).padStart(3,"0");ui.score.textContent=String(Math.floor(score)).padStart(6,"0");ui.distance.textContent=(distance/1000).toFixed(2)+" / "+(finishDistance/1000).toFixed(2)+" KM";ui.courseBar.style.width=Math.min(100,distance/finishDistance*100)+"%";ui.boostBar.style.width=boost+"%";ui.boostValue.textContent=Math.round(boost)+"%";ui.lane.textContent=(rider.lane+1)+" / 3";ui.combo.textContent=combo?"CLEAN LINE ×"+combo:(mode==="racing"?raceModes[selectedMode].label:"RACE READY")}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawWorld();objects.sort((a,b)=>a.y-b.y).forEach(drawObject);drawRider();drawEffects();ctx.restore()}
function path(points,close=true){ctx.beginPath();points.forEach((point,index)=>index?ctx.lineTo(point[0],point[1]):ctx.moveTo(point[0],point[1]));if(close)ctx.closePath()}
function drawWorld(){
  const sky=ctx.createLinearGradient(0,0,0,H*.48);sky.addColorStop(0,"#071522");sky.addColorStop(.5,"#225d76");sky.addColorStop(1,"#e68148");ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
  const glow=ctx.createRadialGradient(W*.78,H*.17,8,W*.78,H*.17,245);glow.addColorStop(0,"rgba(255,235,174,.92)");glow.addColorStop(.24,"rgba(255,166,91,.36)");glow.addColorStop(1,"transparent");ctx.fillStyle=glow;ctx.fillRect(W*.56,0,W*.44,H*.48);ctx.fillStyle="#ffd99b";ctx.beginPath();ctx.arc(W*.78,H*.17,42,0,Math.PI*2);ctx.fill();
  const haze=ctx.createLinearGradient(0,H*.26,0,H*.48);haze.addColorStop(0,"transparent");haze.addColorStop(1,"rgba(224,191,155,.22)");ctx.fillStyle=haze;ctx.fillRect(0,H*.24,W,H*.25);
  ctx.fillStyle="#0b1b22";path([[0,H*.39]]);for(let x=0;x<=W;x+=34)ctx.lineTo(x,H*.345+Math.sin(x*.012)*19+Math.sin(x*.041)*7);ctx.lineTo(W,H*.445);ctx.lineTo(0,H*.445);ctx.fill();
  ctx.fillStyle="#132b32";for(let x=16;x<W;x+=54){const height=14+Math.abs(Math.sin(x))*34;ctx.fillRect(x,H*.39-height,4,height);ctx.beginPath();ctx.arc(x+2,H*.39-height,8,0,Math.PI*2);ctx.fill()}
  const sea=ctx.createLinearGradient(0,H*.39,0,H);sea.addColorStop(0,"#3d7d8d");sea.addColorStop(.25,"#176078");sea.addColorStop(.66,"#093b54");sea.addColorStop(1,"#031923");ctx.fillStyle=sea;ctx.fillRect(0,H*.39,W,H*.61);
  const reflection=ctx.createLinearGradient(W*.72,H*.39,W*.88,H);reflection.addColorStop(0,"rgba(255,188,112,.27)");reflection.addColorStop(1,"transparent");ctx.fillStyle=reflection;path([[W*.69,H*.39],[W*.85,H*.39],[W*.95,H],[W*.53,H]]);ctx.fill();
  const waveCount=Math.round(24*effectsScale);for(let i=0;i<waveCount;i++){const y=H*.405+i*(H*.57/Math.max(1,waveCount)),waveAlpha=.1+i*.006;ctx.strokeStyle=`rgba(205,244,249,${waveAlpha})`;ctx.lineWidth=1+i*.055;ctx.beginPath();for(let x=-20;x<=W+20;x+=effectsScale<.7?34:18){const yy=y+Math.sin(x*.018+frame*.038+i*.8)*(2+i*.22)+Math.sin(x*.055-frame*.02)*2;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy)}ctx.stroke()}
  const glintCount=Math.round(35*effectsScale);for(let i=0;i<glintCount;i++){const x=(i*157+frame*1.5)%(W+240)-120,y=H*.43+(i*47)%(H*.54),len=18+(i%7)*13;ctx.strokeStyle=`rgba(255,255,255,${.035+(i%4)*.018})`;ctx.lineWidth=1+(i%3)*.4;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+len,y+Math.sin(frame*.02+i)*2);ctx.stroke()}
  ctx.setLineDash([25,30]);ctx.strokeStyle="rgba(221,247,250,.26)";ctx.lineWidth=2;[(lanes[0]+lanes[1])/2,(lanes[1]+lanes[2])/2].forEach(y=>{ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()});ctx.setLineDash([]);lanes.forEach((y,index)=>{ctx.fillStyle=index===rider.lane?"rgba(255,91,0,.72)":"rgba(255,255,255,.34)";ctx.font="800 11px Inter";ctx.fillText("LANE "+(index+1),W-82,y-48)});
  const vignette=ctx.createRadialGradient(W*.5,H*.52,H*.15,W*.5,H*.52,H*.82);vignette.addColorStop(.45,"transparent");vignette.addColorStop(1,"rgba(0,7,12,.48)");ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);ctx.fillStyle="rgba(255,255,255,.72)";ctx.font="800 14px Inter";ctx.fillText("WGP#1  ·  WORLD SERIES  ·  PATTAYA",28,H*.445)
}
function drawJetSki(scale,bodyColor,accent,isPlayer=false){
  ctx.save();ctx.scale(scale,scale);
  ctx.fillStyle="rgba(0,10,16,.35)";ctx.beginPath();ctx.ellipse(-18,23,75,15,-.03,0,Math.PI*2);ctx.fill();
  const wake=ctx.createLinearGradient(-150,0,-35,0);wake.addColorStop(0,"transparent");wake.addColorStop(1,"rgba(230,250,255,.78)");ctx.fillStyle=wake;path([[-155,7],[-56,-3],[-46,20],[-136,26]]);ctx.fill();
  const hull=ctx.createLinearGradient(0,-24,0,28);hull.addColorStop(0,bodyColor);hull.addColorStop(.52,bodyColor);hull.addColorStop(.54,"#111b22");hull.addColorStop(1,"#03090d");ctx.fillStyle=hull;path([[-76,7],[-53,-13],[-12,-25],[45,-20],[77,-4],[66,11],[38,25],[-52,24]]);ctx.fill();
  ctx.fillStyle="rgba(255,255,255,.22)";path([[-51,-10],[-9,-20],[48,-16],[61,-8],[-4,-10]]);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.55)";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-65,6);ctx.lineTo(48,2);ctx.stroke();
  ctx.fillStyle=accent;path([[-58,3],[-6,-8],[57,-9],[68,-3],[45,7],[-45,13]]);ctx.fill();ctx.fillStyle="#e9f1f4";path([[43,-12],[67,-5],[61,4],[41,1]]);ctx.fill();
  ctx.fillStyle="#10191f";path([[-25,-23],[0,-42],[43,-37],[49,-18],[11,-12]]);ctx.fill();ctx.fillStyle="#26353e";path([[-1,-39],[34,-35],[34,-28],[3,-29]]);ctx.fill();
  ctx.fillStyle="#080d11";ctx.beginPath();ctx.ellipse(-13,-49,19,12,-.1,0,Math.PI*2);ctx.fill();
  ctx.strokeStyle="#171f24";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(25,-39);ctx.lineTo(36,-58);ctx.lineTo(56,-57);ctx.stroke();ctx.strokeStyle="#c8d4da";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(23,-57);ctx.lineTo(61,-57);ctx.stroke();
  ctx.strokeStyle="#f4f7f8";ctx.lineCap="round";ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(-15,-55);ctx.lineTo(6,-35);ctx.lineTo(25,-55);ctx.stroke();ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(-7,-43);ctx.lineTo(-29,-26);ctx.stroke();
  ctx.fillStyle="#090f13";ctx.beginPath();ctx.arc(-17,-72,14,0,Math.PI*2);ctx.fill();ctx.fillStyle=bodyColor;ctx.beginPath();ctx.arc(-18,-73,11,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.7)";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-28,-70);ctx.lineTo(-7,-70);ctx.stroke();
  ctx.fillStyle="#fff";ctx.font=`900 italic ${isPlayer?18:14}px 'Barlow Condensed'`;ctx.fillText(isPlayer?"WGP#1":"RACING",-43,8);
  ctx.restore()
}
function drawObject(o){ctx.save();ctx.translate(o.x,o.y);if(o.type==="buoy"){
  ctx.fillStyle="rgba(225,248,252,.28)";ctx.beginPath();ctx.ellipse(0,27,34,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="rgba(0,17,25,.28)";ctx.beginPath();ctx.ellipse(0,25,24,7,0,0,Math.PI*2);ctx.fill();
  const buoy=ctx.createLinearGradient(-25,0,25,0);buoy.addColorStop(0,"#8e260b");buoy.addColorStop(.42,"#ff5b00");buoy.addColorStop(.72,"#ff8a34");buoy.addColorStop(1,"#7a1e08");ctx.fillStyle=buoy;path([[0,-47],[17,-34],[27,17],[20,25],[-20,25],[-27,17],[-17,-34]]);ctx.fill();ctx.fillStyle="#f5f7f6";path([[-23,-7],[23,-7],[26,8],[-26,8]]);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.6)";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-8,-39);ctx.lineTo(-14,-14);ctx.stroke();
  }else if(o.type==="rival")drawJetSki(.82,"#d9e2e6","#14b8d4");else{
  const halo=ctx.createRadialGradient(0,-8,30,0,-8,90);halo.addColorStop(0,"rgba(49,231,255,.16)");halo.addColorStop(1,"transparent");ctx.fillStyle=halo;ctx.fillRect(-100,-100,200,190);ctx.strokeStyle="rgba(42,222,246,.38)";ctx.lineWidth=16;ctx.beginPath();ctx.arc(0,-7,57,Math.PI*.08,Math.PI*.92,true);ctx.stroke();ctx.strokeStyle="#92f5ff";ctx.lineWidth=6;ctx.shadowColor="#2de8ff";ctx.shadowBlur=20;ctx.beginPath();ctx.arc(0,-7,57,Math.PI*.08,Math.PI*.92,true);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#07141b";ctx.strokeStyle="#5deeff";ctx.lineWidth=2;[-57,57].forEach(x=>{ctx.beginPath();ctx.roundRect(x-9,-6,18,66,7);ctx.fill();ctx.stroke()});ctx.fillStyle="#e8fcff";ctx.font="800 11px Inter";ctx.textAlign="center";ctx.fillText("BOOST",0,52)}ctx.restore()}
function drawRider(){ctx.save();ctx.translate(rider.x,rider.y-rider.z);ctx.rotate(rider.tilt);if(rider.invuln&&Math.floor(rider.invuln/6)%2)ctx.globalAlpha=.3;drawJetSki(1.05,"#ff5b00","#111b23",true);if(boosting&&boost>0){const flame=ctx.createLinearGradient(-165,0,-66,0);flame.addColorStop(0,"transparent");flame.addColorStop(.55,"rgba(255,102,17,.46)");flame.addColorStop(1,"#ffe58a");ctx.fillStyle=flame;path([[-170,-3],[-69,-10],[-68,10],[-155,16]]);ctx.fill()}ctx.restore()}
function drawEffects(){streaks.forEach(s=>{ctx.globalAlpha=s.life/13;const line=ctx.createLinearGradient(s.x,s.y,s.x+s.w,s.y);line.addColorStop(0,"transparent");line.addColorStop(1,"rgba(226,250,255,.72)");ctx.strokeStyle=line;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x+s.w,s.y);ctx.stroke()});ctx.globalAlpha=1;spray.forEach(p=>{const alpha=Math.max(0,p.life/34),mist=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,p.r*2.2);mist.addColorStop(0,`rgba(238,252,255,${alpha})`);mist.addColorStop(1,"rgba(210,246,255,0)");ctx.fillStyle=mist;ctx.beginPath();ctx.arc(p.x,p.y,p.r*2.2,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;if(boosting&&boost>0){const tunnel=ctx.createRadialGradient(W*.44,H*.57,80,W*.44,H*.57,W*.7);tunnel.addColorStop(0,"transparent");tunnel.addColorStop(1,"rgba(255,91,0,.105)");ctx.fillStyle=tunnel;ctx.fillRect(0,0,W,H)}}
function renderBoard(){const boardMode=document.querySelector('input[name="raceMode"]:checked')?.value||"time",boardDistance=Number(document.querySelector('input[name="raceDistance"]:checked')?.value)||3000,results=board.filter(entry=>(entry.mode||"time")===boardMode&&(entry.distance||3000)===boardDistance).sort((a,b)=>b.score-a.score||a.time-b.time).slice(0,5);ui.board.innerHTML=results.length?results.map((entry,index)=>`<div class="leader-entry"><small>${String(index+1).padStart(2,"0")} · ${raceModes[boardMode].label} · ${boardDistance/1000} KM</small><strong>${entry.name.replace(/[<>&]/g,"")}</strong><span>${entry.score.toLocaleString()}</span></div>`).join(""):"<div class=\"leader-empty\">NO RESULTS FOR THIS MODE &amp; DISTANCE</div>"}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(mode!=="menu"&&mode!=="paused"){update(dt);draw()}requestAnimationFrame(loop)}

const keys={ArrowUp:"lane-up",ArrowDown:"lane-down",KeyW:"lane-up",KeyS:"lane-down",Space:"jump",ShiftLeft:"boost",ShiftRight:"boost"};addEventListener("keydown",event=>{if(keys[event.code]){event.preventDefault();action(keys[event.code],true)}if(event.code==="Escape"&&mode==="paused")togglePause(false);if(event.code==="KeyP"&&mode!=="menu")togglePause();if(event.code==="KeyR"&&mode!=="menu")openRace()});addEventListener("keyup",event=>{if(keys[event.code]==="boost")action("boost",false)});
const activeBoostPointers=new Set();document.querySelectorAll("[data-action]").forEach(button=>{const name=button.dataset.action;const release=event=>{button.classList.remove("active");if(name==="boost"){activeBoostPointers.delete(event.pointerId);if(!activeBoostPointers.size)action("boost",false)}};button.addEventListener("pointerdown",event=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);button.classList.add("active");if(name==="boost")activeBoostPointers.add(event.pointerId);action(name,true)});button.addEventListener("pointerup",release);button.addEventListener("pointercancel",release);button.addEventListener("lostpointercapture",release)});
$("#enterRace").addEventListener("click",openRace);$("#raceAgain").addEventListener("click",openRace);$("#backHome").addEventListener("click",backHome);$("#pauseHome").addEventListener("click",backHome);$("#resumeGame").addEventListener("click",()=>togglePause(false));ui.pauseButton.addEventListener("click",()=>togglePause());if(ui.frame.requestFullscreen)ui.fullscreenButton.addEventListener("click",toggleFullscreen);else ui.fullscreenButton.hidden=true;document.addEventListener("fullscreenchange",updateFullscreenButton);document.addEventListener("visibilitychange",()=>{if(document.hidden&&["racing","countdown"].includes(mode))togglePause(true)});document.querySelectorAll('input[name="raceMode"],input[name="raceDistance"]').forEach(input=>input.addEventListener("change",renderBoard));ui.name.addEventListener("keydown",event=>{if(event.key==="Enter")openRace()});renderBoard();requestAnimationFrame(loop);
