"use strict";

const canvas=document.querySelector("#game");
const ctx=canvas.getContext("2d");
const $=selector=>document.querySelector(selector);
const W=canvas.width,H=canvas.height,FINISH=3000;
const lanes=[H*.50,H*.64,H*.78];
const ui={home:$("#homeScreen"),race:$("#raceScreen"),result:$("#resultScreen"),name:$("#playerName"),speed:$("#speed"),score:$("#score"),distance:$("#distance"),courseBar:$("#courseBar"),boostBar:$("#boostBar"),boostValue:$("#boostValue"),combo:$("#combo"),callout:$("#callout"),countdown:$("#countdown"),board:$("#leaderboard")};

let mode="menu",last=performance.now(),frame=0,distance=0,score=0,speed=96,topSpeed=96,boost=30,boosting=false,combo=0,passes=0,shake=0,spawnClock=0,gateClock=0,calloutTimer=0,countValue=3,countTimer=0;
let objects=[],spray=[],streaks=[];
let board=readBoard();
const rider={lane:1,x:W*.20,y:lanes[1],targetY:lanes[1],z:0,vz:0,tilt:0,invuln:0};

function readBoard(){try{return JSON.parse(localStorage.getItem("wgp1_time_attack_board")||"[]")}catch{return[]}}
function riderName(){return(ui.name.value.trim().replace(/[^\p{L}\p{N} _-]/gu,"").slice(0,14)||"WGP RIDER").toUpperCase()}
function resetRace(){frame=0;distance=score=combo=passes=shake=spawnClock=gateClock=calloutTimer=0;speed=topSpeed=96;boost=30;boosting=false;objects=[];spray=[];streaks=[];rider.lane=1;rider.y=rider.targetY=lanes[1];rider.z=rider.vz=0;rider.invuln=0;updateUI()}
function openRace(){resetRace();mode="countdown";ui.home.hidden=true;$("#leaderboardSection").hidden=true;ui.race.classList.add("active");ui.race.setAttribute("aria-hidden","false");ui.result.classList.remove("active");countValue=3;countTimer=0;showCount("3")}
function backHome(){mode="menu";boosting=false;ui.race.classList.remove("active");ui.race.setAttribute("aria-hidden","true");ui.result.classList.remove("active");ui.home.hidden=false;$("#leaderboardSection").hidden=false;renderBoard()}
function showCount(value){ui.countdown.textContent=value;ui.countdown.classList.remove("on");void ui.countdown.offsetWidth;ui.countdown.classList.add("on")}
function action(name,on=true){if(mode!=="racing")return;if(name==="left"&&on&&rider.lane>0){rider.lane--;rider.targetY=lanes[rider.lane]}if(name==="right"&&on&&rider.lane<2){rider.lane++;rider.targetY=lanes[rider.lane]}if(name==="jump"&&on&&rider.z===0)rider.vz=19;if(name==="boost")boosting=on}
function spawnObstacle(){const lane=Math.floor(Math.random()*3),rival=Math.random()<.37;objects.push({type:rival?"rival":"buoy",lane,x:W+150,y:lanes[lane],w:rival?125:48,phase:Math.random()*6,passed:false});if(distance>900&&Math.random()<.32){const other=(lane+1+Math.floor(Math.random()*2))%3;objects.push({type:"buoy",lane:other,x:W+150,y:lanes[other],w:48,phase:0,passed:false})}}
function spawnGate(){const lane=Math.floor(Math.random()*3);objects.push({type:"gate",lane,x:W+120,y:lanes[lane],w:110,phase:0,passed:false})}
function flash(message){ui.callout.textContent=message;ui.callout.classList.add("show");calloutTimer=82}
function crash(){if(rider.invuln>0)return;rider.invuln=100;shake=20;speed=Math.max(70,speed-35);boost=Math.max(0,boost-22);combo=0;flash("CONTACT · SPEED LOST");for(let i=0;i<28;i++)spray.push({x:rider.x,y:rider.y-rider.z,vx:(Math.random()-.5)*12,vy:-Math.random()*10,r:2+Math.random()*6,life:34})}
function finish(){mode="finished";boosting=false;const finalScore=Math.floor(score),entry={name:riderName(),score:finalScore,time:Date.now()};board.push(entry);board.sort((a,b)=>b.score-a.score||a.time-b.time);board=board.slice(0,10);localStorage.setItem("wgp1_time_attack_board",JSON.stringify(board));const position=board.findIndex(item=>item.time===entry.time)+1;$("#resultScore").textContent=finalScore.toLocaleString();$("#resultRider").textContent=entry.name;$("#resultPasses").textContent=passes;$("#resultSpeed").textContent=Math.round(topSpeed)+" KM/H";$("#resultPosition").textContent="#"+position;ui.result.classList.add("active");ui.result.setAttribute("aria-hidden","false")}

function update(dt){frame++;if(mode==="countdown"){countTimer+=dt;if(countTimer>.72){countTimer=0;countValue--;if(countValue>0)showCount(countValue);else if(countValue===0)showCount("GO!");else mode="racing"}}
  const racing=mode==="racing",usingBoost=racing&&boosting&&boost>0,target=usingBoost?182:126;speed+=(racing?(target-speed)*.018:(96-speed)*.02)*dt*60;topSpeed=Math.max(topSpeed,speed);if(usingBoost)boost=Math.max(0,boost-.27*dt*60);else if(racing)boost=Math.min(100,boost+.04*dt*60);if(boost<=0)boosting=false;
  if(racing){distance+=speed*.0085*dt*60;score+=speed*.0108*dt*60*(1+Math.min(combo,10)*.055);spawnClock+=dt*60;gateClock+=dt*60;const gap=Math.max(58,112-distance/45);if(spawnClock>gap){spawnClock=0;spawnObstacle()}if(gateClock>300){gateClock=0;spawnGate()}if(distance>=FINISH)finish()}
  rider.y+=(rider.targetY-rider.y)*.20*dt*60;if(rider.z>0||rider.vz>0){rider.vz-=1.12*dt*60;rider.z+=rider.vz*dt*60;if(rider.z<=0){rider.z=0;rider.vz=0;for(let i=0;i<12;i++)spray.push({x:rider.x,y:rider.y,vx:-Math.random()*7,vy:-Math.random()*5,r:2+Math.random()*4,life:24})}}rider.tilt+=(Math.sign(rider.targetY-rider.y)*.16-rider.tilt)*.13;if(rider.invuln>0)rider.invuln-=dt*60;
  const scroll=speed*.13*dt*60;objects.forEach(o=>{o.x-=scroll;if(o.type==="rival")o.y=lanes[o.lane]+Math.sin(frame*.034+o.phase)*13;const same=Math.abs(rider.y-o.y)<44,close=o.x<rider.x+72&&o.x+o.w>rider.x-64;if(racing&&!o.passed&&o.x+o.w<rider.x-55){o.passed=true;if(o.type==="gate"&&same){score+=500;boost=Math.min(100,boost+30);combo++;passes++;flash("BOOST GATE +500")}else if(o.type!=="gate"){passes++;if(Math.abs(rider.y-o.y)<100){score+=250;boost=Math.min(100,boost+10);combo++;flash("NEAR MISS +250")}else{score+=80;combo++}}}if(racing&&close&&same&&rider.z<42&&o.type!=="gate")crash()});objects=objects.filter(o=>o.x>-200);
  if(racing&&frame%3===0){spray.push({x:rider.x-48,y:rider.y-rider.z+18,vx:-7-Math.random()*7,vy:-1-Math.random()*4,r:2+Math.random()*5,life:23});if(speed>145)streaks.push({x:W+20,y:H*.32+Math.random()*H*.58,w:80+Math.random()*180,life:13})}spray.forEach(p=>{p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.vy+=.27*dt*60;p.life-=dt*60});spray=spray.filter(p=>p.life>0);streaks.forEach(s=>{s.x-=34*dt*60;s.life-=dt*60});streaks=streaks.filter(s=>s.life>0);shake*=.82;if(calloutTimer>0)calloutTimer-=dt*60;else ui.callout.classList.remove("show");updateUI()}

function updateUI(){ui.speed.textContent=String(Math.round(speed)).padStart(3,"0");ui.score.textContent=String(Math.floor(score)).padStart(6,"0");ui.distance.textContent=(distance/1000).toFixed(2)+" / 3.00 KM";ui.courseBar.style.width=Math.min(100,distance/FINISH*100)+"%";ui.boostBar.style.width=boost+"%";ui.boostValue.textContent=Math.round(boost)+"%";ui.combo.textContent=combo?"CLEAN LINE ×"+combo:(mode==="racing"?"PUSH THE LIMIT":"RACE READY")}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawWorld();objects.sort((a,b)=>a.y-b.y).forEach(drawObject);drawRider();drawEffects();ctx.restore()}
function drawWorld(){const sky=ctx.createLinearGradient(0,0,0,H*.55);sky.addColorStop(0,"#06101a");sky.addColorStop(.55,"#226078");sky.addColorStop(1,"#db713c");ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle="#ffbc70";ctx.beginPath();ctx.arc(W*.78,H*.18,58,0,Math.PI*2);ctx.fill();const glow=ctx.createRadialGradient(W*.78,H*.18,25,W*.78,H*.18,230);glow.addColorStop(0,"rgba(255,127,55,.38)");glow.addColorStop(1,"transparent");ctx.fillStyle=glow;ctx.fillRect(W*.56,0,W*.44,H*.48);ctx.fillStyle="#07131b";ctx.beginPath();ctx.moveTo(0,H*.39);for(let x=0;x<=W;x+=50)ctx.lineTo(x,H*.35+Math.sin(x*.015)*24+Math.sin(x*.04)*10);ctx.lineTo(W,H*.48);ctx.lineTo(0,H*.48);ctx.fill();const sea=ctx.createLinearGradient(0,H*.4,0,H);sea.addColorStop(0,"#27647b");sea.addColorStop(.47,"#0a354d");sea.addColorStop(1,"#031720");ctx.fillStyle=sea;ctx.fillRect(0,H*.39,W,H*.61);ctx.strokeStyle="rgba(161,228,240,.24)";ctx.lineWidth=2;for(let i=0;i<18;i++){const y=H*.42+i*29;ctx.beginPath();for(let x=0;x<=W;x+=22){const yy=y+Math.sin(x*.019+frame*.043+i)*6;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy)}ctx.stroke()}ctx.fillStyle="rgba(255,255,255,.045)";ctx.fillRect(0,lanes[0]-55,W,110);ctx.fillRect(0,lanes[2]-55,W,110);ctx.setLineDash([22,24]);ctx.strokeStyle="rgba(255,255,255,.16)";[(lanes[0]+lanes[1])/2,(lanes[1]+lanes[2])/2].forEach(y=>{ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()});ctx.setLineDash([]);ctx.fillStyle="rgba(255,255,255,.68)";ctx.font="800 15px Inter";ctx.fillText("WGP#1  ·  WORLD SERIES  ·  PATTAYA",28,H*.45)}
function drawObject(o){ctx.save();ctx.translate(o.x,o.y);if(o.type==="buoy"){ctx.fillStyle="rgba(255,255,255,.33)";ctx.beginPath();ctx.ellipse(0,30,31,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ff5b00";ctx.beginPath();ctx.moveTo(0,-43);ctx.lineTo(25,24);ctx.lineTo(-25,24);ctx.closePath();ctx.fill();ctx.fillStyle="#fff";ctx.fillRect(-20,-5,40,9)}else if(o.type==="rival"){ctx.fillStyle="rgba(255,255,255,.35)";ctx.beginPath();ctx.ellipse(-28,22,58,11,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#dae4e9";ctx.beginPath();ctx.moveTo(-58,8);ctx.lineTo(-22,-23);ctx.lineTo(54,-14);ctx.lineTo(65,0);ctx.lineTo(36,19);ctx.lineTo(-40,20);ctx.closePath();ctx.fill();ctx.fillStyle="#14232d";ctx.fillRect(-4,-31,34,15);ctx.fillStyle="#33d5ef";ctx.fillRect(35,-10,19,6)}else{ctx.strokeStyle="rgba(41,231,255,.9)";ctx.lineWidth=10;ctx.shadowColor="#29e7ff";ctx.shadowBlur=20;ctx.beginPath();ctx.arc(0,-10,54,Math.PI*.12,Math.PI*.88,true);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.font="800 12px Inter";ctx.textAlign="center";ctx.fillText("BOOST GATE",0,48)}ctx.restore()}
function drawRider(){ctx.save();ctx.translate(rider.x,rider.y-rider.z);ctx.rotate(rider.tilt);if(rider.invuln&&Math.floor(rider.invuln/6)%2)ctx.globalAlpha=.3;ctx.fillStyle="rgba(255,255,255,.44)";ctx.beginPath();ctx.ellipse(-38,24,68,13,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ff5b00";ctx.beginPath();ctx.moveTo(-73,9);ctx.lineTo(-30,-27);ctx.lineTo(54,-17);ctx.lineTo(75,-1);ctx.lineTo(41,22);ctx.lineTo(-48,23);ctx.closePath();ctx.fill();ctx.fillStyle="#071018";ctx.beginPath();ctx.moveTo(-20,-25);ctx.lineTo(7,-43);ctx.lineTo(47,-34);ctx.lineTo(40,-15);ctx.closePath();ctx.fill();ctx.fillStyle="#fff";ctx.font="900 italic 18px 'Barlow Condensed'";ctx.fillText("WGP#1",-38,10);ctx.fillStyle="#081018";ctx.beginPath();ctx.arc(-16,-64,14,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#f7fafc";ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-13,-49);ctx.lineTo(6,-25);ctx.lineTo(24,-48);ctx.stroke();if(boosting&&boost>0){ctx.strokeStyle="#ffca43";ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-74,4);ctx.lineTo(-142,4);ctx.stroke()}ctx.restore()}
function drawEffects(){streaks.forEach(s=>{ctx.globalAlpha=s.life/13;ctx.strokeStyle="#fff";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x+s.w,s.y);ctx.stroke()});ctx.globalAlpha=1;spray.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/34);ctx.fillStyle="#d8f7ff";ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;if(boosting&&boost>0){ctx.fillStyle="rgba(255,91,0,.07)";ctx.fillRect(0,0,W,H)}}
function renderBoard(){ui.board.innerHTML=board.length?board.slice(0,5).map((entry,index)=>`<div class="leader-entry"><small>${String(index+1).padStart(2,"0")}</small><strong>${entry.name.replace(/[<>&]/g,"")}</strong><span>${entry.score.toLocaleString()}</span></div>`).join(""):"<div class=\"leader-empty\">NO RACE RESULTS YET</div>"}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(mode!=="menu"){update(dt);draw()}requestAnimationFrame(loop)}

const keys={ArrowLeft:"left",ArrowRight:"right",ArrowUp:"jump",Space:"jump",ShiftLeft:"boost",ShiftRight:"boost"};addEventListener("keydown",event=>{if(keys[event.code]){event.preventDefault();action(keys[event.code],true)}if(event.code==="KeyR"&&mode!=="menu")openRace()});addEventListener("keyup",event=>{if(keys[event.code]==="boost")action("boost",false)});document.querySelectorAll("[data-action]").forEach(button=>{const name=button.dataset.action;button.addEventListener("pointerdown",event=>{event.preventDefault();action(name,true)});button.addEventListener("pointerup",()=>action(name,false));button.addEventListener("pointercancel",()=>action(name,false))});
$("#enterRace").addEventListener("click",openRace);$("#raceAgain").addEventListener("click",openRace);$("#backHome").addEventListener("click",backHome);ui.name.addEventListener("keydown",event=>{if(event.key==="Enter")openRace()});renderBoard();requestAnimationFrame(loop);
